/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final.Views;

import proyecto_final.Models.TacoState;
import proyecto_final.controllers.TacoController;

/**
 *
 * @author fedea
 */
public class TacosView extends javax.swing.JFrame {

    /**
     * Creates new form TacosView
     */
    public TacosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnUpdateState = new javax.swing.JButton();
        btnUpdateDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new TacoTableModel("Tacos by State", TacoState.Pedido));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido", "En Preparacion", "Para Retirar", "Entregado", "Todos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnUpdateState.setText("Actualizar Estado de Taco");
        btnUpdateState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStateActionPerformed(evt);
            }
        });

        btnUpdateDB.setText("Actualizar Base de Datos");
        btnUpdateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnUpdateState)
                .addGap(61, 61, 61)
                .addComponent(btnUpdateDB)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateState)
                    .addComponent(btnUpdateDB))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String s = (String) this.jComboBox1.getSelectedItem();
        switch (s) {
            case "Pedido": {
                this.jTable1.setModel(new TacoTableModel("Tacos by State", TacoState.Pedido));
                this.jTable1.updateUI();
                break;
            }
            case "En Preparacion": {
                this.jTable1.setModel(new TacoTableModel("Tacos by State", TacoState.EnPreparacion));
                break;
            }
            case "Para Retirar": {
                this.jTable1.setModel(new TacoTableModel("Tacos by State", TacoState.ParaRetirar));
                this.jTable1.updateUI();
                break;
            }
            case "Entregado": {
                this.jTable1.setModel(new TacoTableModel("Tacos by State", TacoState.Entregado));
                this.jTable1.updateUI();
                break;
            }
            case "Todos": {
                this.jTable1.setModel(new TacoTableModel());
                this.jTable1.updateUI();
                break;
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnUpdateStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStateActionPerformed
        int row = this.jTable1.getSelectedRow();
        if (row != -1) {
            TacoState s = (TacoState) this.jTable1.getValueAt(row, 6);
            switch (s) {
                case Pedido: {
                    this.tacoController.updateStateTaco((Long) this.jTable1.getValueAt(row, 0), TacoState.EnPreparacion);

                    break;
                }
                case EnPreparacion: {
                    this.tacoController.updateStateTaco((Long) this.jTable1.getValueAt(row, 0), TacoState.ParaRetirar);

                    break;
                }
                case ParaRetirar: {
                    this.tacoController.updateStateTaco((Long) this.jTable1.getValueAt(row, 0), TacoState.Entregado);

                    break;
                }

            }
        }
        this.jTable1.updateUI();
    }//GEN-LAST:event_btnUpdateStateActionPerformed

    private void btnUpdateDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDBActionPerformed
        this.jTable1.updateUI();
    }//GEN-LAST:event_btnUpdateDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TacosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TacosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TacosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TacosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TacosView().setVisible(true);
            }
        });
    }
    private final TacoController tacoController = new TacoController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateDB;
    private javax.swing.JButton btnUpdateState;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
